name: Currency Action
inputs:
  to_currency:
    description: Currency Code that you would like to convert to
    required: true
    default: 'THB'
  from_currency:
    description: Currency Code that you would like to convert from
    required: true
    default: 'EUR'
  output:
    description: "Output options: 1) response = return human-readable sentence 2) rate = to return only rate number"
    required: false
    default: 'response'

runs:
  using: docker
  image: Dockerfile
  
